name: qr_factory
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_auth: ^4.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.0.2
  image: ^4.0.15
  image_picker: ^0.8.7+2
  line_icons: ^2.0.1
  qr_flutter: ^4.0.0
  # qr_flutter:
  #   git:
  #     url: git://github.com/lukef/qr.flutter.git

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
